version: "3"

services:
  mongodb1:
    image: mongo
    container_name: mongodb1
    restart: always
    command: mongod --replSet rs0 --port 30000
    ports:
      - 30000:30000
    volumes:
      - ./mongo/mongodb1:/data/db

  mongodb2:
    image: mongo
    container_name: mongodb2
    restart: always
    command: mongod --replSet rs0 --port 30001
    ports:
      - 30001:30001
    volumes:
      - ./mongo/mongodb2:/data/db
    depends_on:
      - mongodb1

  mongodb3:
    image: mongo
    container_name: mongodb3
    restart: always
    command: mongod --replSet rs0 --port 30002
    ports:
      - 30002:30002
    volumes:
      - ./mongo/mongodb3:/data/db
    depends_on:
      - mongodb2